name: Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                 submodules: recursive

            - name: Install dependencies
              run: |
                   sudo apt-get update
                   sudo apt-get install -y gcc-10 g++-10 build-essential libsdl2-dev \
                   nvidia-cuda-toolkit

            - name: Compile and run
              run: make run-video

            - name: Upload artifact (build/output.gif)
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: build/output.gif
