name: Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                 submodules: recursive

            - name: Install gcc-10 and SDL2
              run: |
                   sudo apt-get update
                   sudo apt-get install -y gcc-10 build-essential libsdl2-dev

            - name: Compile
              run: make dry-run
