name: Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                 submodules: recursive

            - name: Install gcc-10 and SDL2
              run: |
                   sudo apt-get update
                   sudo apt-get install -y gcc-10 build-essential libsdl2-dev

            - name: Cache build
              uses: actions/cache@v3
              with:
                path: build
                key: ${{ runner.os }}-make-${{ hashFiles('src/**/*.cpp', 'src/**/*.cu', 'imgui/**/*.cpp', 'Makefile') }}
                restore-keys: ${{ runner.os }}-make-

            - name: Compile and run
              run: make run-video

            - name: Upload artifact (build/output.gif)
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: build/output.gif
